package admin

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"testing"

	"github.com/stretchr/testify/assert"
)

// Verifier generated by a real PostgreSQL 16 instance
// (password_encryption='scram-sha-256') for role "scramuser", password
// "pencil". The two key fields were independently reproduced from RFC 5802 /
// RFC 7677 math against this verifier, so it is not a self-asserted value.
const pg16SCRAMVerifier = "SCRAM-SHA-256$4096:2ZwmEXiMTFGPn5dT2IsWlg==$JSGFrq62lXpimJr581zcZrQK5Eqo4GiSehVu6/cFSpc=:ChGrZ2PU95ScEIeCpA7XJoBotE04SAmg4nAY8zezFs8="

// Verifier generated by a real PostgreSQL 16 instance
// (password_encryption='md5') for role "md5_vectest_1159", password "secret".
const pg16MD5Verifier = "md57aeeb6edc06149896bb7700192ed0912"

func TestComparePasswordSCRAMSHA256(t *testing.T) {
	ui := UserInfo{Username: "scramuser", PasswordHash: pg16SCRAMVerifier}

	assert.Equal(t, PasswordMatchOK, ui.ComparePassword("pencil"))
	assert.Equal(t, PasswordMismatch, ui.ComparePassword("wrong-password"))
}

func TestComparePasswordSCRAMSHA256UsernameIndependent(t *testing.T) {
	// scram verifiers do not fold the username in (unlike md5), so a role
	// renamed after the password was set still matches.
	ui := UserInfo{Username: "renamed-role", PasswordHash: pg16SCRAMVerifier}
	assert.Equal(t, PasswordMatchOK, ui.ComparePassword("pencil"))
}

func TestComparePasswordMD5(t *testing.T) {
	ui := UserInfo{Username: "md5_vectest_1159", PasswordHash: pg16MD5Verifier}

	assert.Equal(t, PasswordMatchOK, ui.ComparePassword("secret"))
	assert.Equal(t, PasswordMismatch, ui.ComparePassword("Secret"))

	// md5 hashes include the username, so the same password for another role
	// must not match.
	other := UserInfo{Username: "someone-else", PasswordHash: pg16MD5Verifier}
	assert.Equal(t, PasswordMismatch, other.ComparePassword("secret"))
}

func TestComparePasswordUnknownFormats(t *testing.T) {
	for _, hash := range []string{
		"",
		"plaintext-password",
		"SCRAM-SHA-256$garbage",
		"SCRAM-SHA-256$0:2ZwmEXiMTFGPn5dT2IsWlg==$JSGFrq62lXpimJr581zcZrQK5Eqo4GiSehVu6/cFSpc=:ChGrZ2PU95ScEIeCpA7XJoBotE04SAmg4nAY8zezFs8=",
		"SCRAM-SHA-256$4096:!!!!$AAAA:AAAA",
		"SCRAM-SHA-256$4096:2ZwmEXiMTFGPn5dT2IsWlg==$AAAA",
	} {
		ui := UserInfo{Username: "u", PasswordHash: hash}
		assert.Equal(t, PasswordMatchUnknown, ui.ComparePassword("pencil"), "hash %q", hash)
	}
}

func TestPBKDF2HMACSHA256KnownAnswers(t *testing.T) {
	// RFC 7914 section 11 test vectors for PBKDF2-HMAC-SHA-256.
	one := pbkdf2HMACSHA256([]byte("password"), []byte("salt"), 1, 32)
	assert.Equal(t, "120fb6cffcf8b32c43e7225256c4f837a86548c92ccc35480805987cb70be17b", hex.EncodeToString(one))

	fourK := pbkdf2HMACSHA256([]byte("password"), []byte("salt"), 4096, 32)
	assert.Equal(t, "c5e478d59288c841aa530db6845c4c8d962893a001ce4e11a4963873aa98134a", hex.EncodeToString(fourK))
}

func TestPBKDF2DerivesKeysMatchingPGVerifier(t *testing.T) {
	salt, err := base64.StdEncoding.DecodeString("2ZwmEXiMTFGPn5dT2IsWlg==")
	assert.NoError(t, err)

	saltedPassword := pbkdf2HMACSHA256([]byte("pencil"), salt, 4096, sha256.Size)
	clientKey := hmacSHA256(saltedPassword, []byte("Client Key"))
	storedKey := sha256.Sum256(clientKey)
	serverKey := hmacSHA256(saltedPassword, []byte("Server Key"))

	assert.Equal(t, "JSGFrq62lXpimJr581zcZrQK5Eqo4GiSehVu6/cFSpc=",
		base64.StdEncoding.EncodeToString(storedKey[:]))
	assert.Equal(t, "ChGrZ2PU95ScEIeCpA7XJoBotE04SAmg4nAY8zezFs8=",
		base64.StdEncoding.EncodeToString(serverKey))

	// sanity: the derivation depends on the password.
	other := pbkdf2HMACSHA256([]byte("not-pencil"), salt, 4096, sha256.Size)
	assert.False(t, hmac.Equal(other, saltedPassword))
}
